DjangoApp/core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('tunes/', include('tunes.urls', namespace='tunes')),
]

DjangoApp/main/urls.py
from django.urls import path
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('music/', views.music_home, name='music_home'),
    path('adminlinks/', views.admin_links, name="admin_links"),
    path('dbjson/', views.dbjson, name="dbjson"),
]

DjangoApp/tunes/urls.py
from django.urls import path
from tunes import views

app_name = 'tunes'
urlpatterns = [
    path('list/', views.list, name='list'),
    path('<int:pk>/', views.detail, name='detail'),
]

DjangoApp/templates/admin_links.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<h1>Admin Links</h1>
<hr>
<div class="row">
    <div class="col text-center">
        <a class="btn btn-outline-dark btn-lg" href="{% url 'main:dbjson'%}">
            Download ClaytonCook.com Database JSON
        </a>
    </div>
</div>

{%endblock %}

DjangoApp/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'main/cc_cog.svg' %}">

    <title>Clayton S. Cook</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>

    <!-- Font Awsome-->
    <script src="https://kit.fontawesome.com/0f74d8f617.js" crossorigin="anonymous"></script>

    <!-- Custom styles for this template -->
    <link href="{% static 'main/css/styles.css' %}" rel="stylesheet">
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light rounded">
        <a class="navbar-brand" href="{% url 'main:home' %}">
          <img id='main-icon' src="{% static 'main/cc_cog_order_to_disorder.svg' %}" alt="">
        </a>
        <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample09">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link color-me" href="{% url 'main:home' %}#portfolio">Portfolio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:music_home' %}">Music</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tunes:list' %}">Tunes</a>
            </li>
            {% if request.user.is_superuser %}
            <li>
              <a class="nav-link" href="{% url 'main:admin_links' %}">AdminLinks</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    
      <div 
        class="container col-xl-10 col-lg-12 col-md-12 mx-auto"
        style=""
      >
      {% block content %}{% endblock %}
      </div>

    </div>

    <footer>
        <div class="container">
          <p class="m-0 m-5 text-center">Created by <a href="https://github.com/claytoncook12" target="_blank">claytoncook12</a> - 2021</p>
        </div>
        <!-- /.container -->
    </footer>
    
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

DjangoApp/templates/home.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<main role="main">
  <div class="jumbotron">
    <div class="col-md-12 mx-auto text-center text-black">
      <h1 class="name-bold">Clayton S. Cook, P.E.</h1>
      <h2>Civil Engineer - Aspiring Developer</h2>
      <div class="divider-custom">
        <div class="divider-custom-line">________________________</div>
      </div>
      <img 
        id="main-image"
        class="mx-auto"
        style="
          display: block;
          margin-left: auto;
          margin-right: auto;
          width: 60%;
        "
        src="{% static 'main/clayton_cook_head_shot.png' %}"
        alt="clayton_cook_head_shot" 
      />
      <div class="row mx-auto" id="personal_links">
        <div class="col-md-4">
          <a href="{% static 'main/_2021-10-21 Clayton S. Cook CV.pdf' %}" target="_blank" class="btn btn-primary btn-lg border-dark" id='resume'>CV</a>
        </div>
        <div class='col-md-4'>
          <a href='https://github.com/claytoncook12' target="_blank"><i class="fab fa-github fa-3x"></i></a>
        </div>
        <div class='col-md-4'>
          <a href='https://www.linkedin.com/in/clayton-cook-a5580298/' target="_blank"><i class="fab fa-linkedin fa-3x" href='https://www.linkedin.com/in/clayton-cook-a5580298/'></i></a>
        </div>
      </div>
      <br>
      <h5>
        A trained geotechnical engineer who loves to collect data, organize it and bring it to life
        through web-based Python solutions. My current role at the Kentucky Transportation Cabinet has me
        doing geotechnical design work, but I’m looking to transition into a position that is focused around
        making web or programmatic based solutions.
        <br>
        <br>
        Please look at my current portfolio and skills below.
      </h5>
    </div>
  </div>
</main>

<section id='portfolio'>
  <h2 id='section-header'>Portfolio</h2>
  <hr>
  <div id='projects-col' class="row mx-auto">
    <!-- Card -->
    <div class="card bg-light col-md-4">
      <a href="https://main.dotbwxbwz8gqn.amplifyapp.com" target="_blank">
        <img class="card-img-top" src="{% static 'main/projects/AutoFoinnSesiun_750x750.png' %}" alt="Card image cap">
      </a>
      <div class="card-body">
        <h5 class="card-title"><b>Auto Foinn Seisiún 1</b></h5>
        <h6>
          <a href="https://github.com/claytoncook12/AutoFoinnSeisiun" target="_blank">
            Source Code
          </a>
        </h6>
        <h6><i>skills: html, css, javascript</i></h6>
        <p class="card-text">A single page web application for playing the sessions
          that were put together in 
          <a href="https://comhaltas.ie/shop/detail/foinn_seisiun_book_volume_1/" target="_blank">
            Foinn Seisiún Book - Volume 1
          </a>. Comhaltas Ceoltóirí Éireann is a organization that promotes traditional Irish music.
          These cd set is are a must know for musicians who enjoy session playing and would like
          to build a repertoire of tunes which will be universally known.
        </p>
      </div>
    </div>
    <!-- Card -->
    <div class="card bg-light col-md-4">
      <a href="http://www.vgsdb.com" target="_blank">
        <img class="card-img-top" src="{% static 'main/projects/vgsdb_750x750.png' %}" alt="Card image cap">
      </a>
      <div class="card-body">
        <h5 class="card-title"><b>www.vgsdb.com</b></h5>
        <h6>
          <a href="https://github.com/claytoncook12/VGSDBWebsite" target="_blank">
            Source Code
          </a>
        </h6>
        <h6><i>skills: django, database design, aws elasticbeanstalk</i></h6>
        <p class="card-text">A website for organizing tunes played on a online Irish session.
          Used the Django web framework and AWS elasticbeanstalk.
        </p>
      </div>
    </div>
    <!-- Card -->
    <div class="card bg-light col-md-4">
      <a href="http://ec2-54-89-158-149.compute-1.amazonaws.com:8000/" target="_blank">
        <img class="card-img-top" src="{% static 'main/projects/AutoSessionMVP_750x750.PNG' %}" alt="Card image cap">
      </a>
      <div class="card-body">
        <h5 class="card-title"><b>PDMAutoSession</b></h5>
        <h6>
          <a href="https://github.com/claytoncook12/PDMAutoSession" target="_blank">
            Source Code
          </a>
        </h6>
        <h6><i>skills: django, docker, javascript, aws ec2</i></h6>
        <p class="card-text">A MVP website developed in Python Developer Mindset Program
          for mixing and matching audio files of different Irish tunes to play along with.
        </p>
      </div>
    </div>
    <!-- Card -->
    <div class="card bg-light col-md-4">
      <a href="http://carcassonnelane.pythonanywhere.com/" target="_blank">
        <img class="card-img-top" src="{% static 'main/projects/CarcassonneLaneWebsite_RAwY2ne.jpg' %}" alt="Card image cap">
      </a>
      <div class="card-body">
        <h5 class="card-title"><b>CarcassoneLane</b></h5>
        <h6>
          <a href="https://github.com/claytoncook12/TheLaneCarcassonne" target="_blank">
            Source Code
          </a>
        </h6>
        <h6><i>skill: flask</i></h6>
        <p class="card-text">Personal website to keep track of Carcassone
        games that we play at the house. Written with the Flask framework
        and deployed on <a href="https://www.pythonanywhere.com/">PythonAnywhere.</a>
        </p>
      </div>
    </div>
    <!-- Card -->
    <div class="card bg-light col-md-4">
      <a href="https://github.com/claytoncook12/DataQuest_DataEngineering_GuidedProjects/blob/main/Guided%20Project%20-%20Hacker%20News%20Pipeline.ipynb" target="_blank">
        <img class="card-img-top" src="{% static 'main/projects/Guided_Project_-_Hacker_News_Pipeline.png' %}" alt="Card image cap">
      </a>
      <div class="card-body">
        <h5 class="card-title"><b>Data Pipeline Creation</b></h5>
        <h6><i>skill: pipeline</i></h6>
        <p class="card-text">This was a project completed in the DataQuest.io DataEngineering Career Path program.</p>
      </div>
    </div>
    <!-- Card -->
    <div class="card bg-light col-md-4">
      <a href="https://github.com/claytoncook12/DataQuest_DataEngineering_GuidedProjects/blob/main/Guided%20Project%20-%20Implementing%20A%20Key-Value%20Database.ipynb" target="_blank">
        <img class="card-img-top" src="{% static 'main/projects/Guided_Project_-_Implementing_A_Key-Val.png' %}" alt="Card image cap">
      </a>
      <div class="card-body">
        <h5 class="card-title"><b>Implementing A Key-Value Database</b></h5>
        <h6><i>skill: database</i></h6>
        <p class="card-text">This was a project completed in the DataQuest.io 
          Data Engineering Career Path program</p>
      </div>
    </div>
    <!-- Card -->
    <div class="card bg-light col-md-4">
      <a href="https://github.com/claytoncook12/DataQuest_DataEngineering_GuidedProjects/blob/main/Guided%20Project%20-%20Answering%20Business%20Questions%20using%20SQL.ipynb" target="_blank">
        <img class="card-img-top" src="{% static 'main/projects/DataQuest_Answering_Business_Que.png' %}" alt="Card image cap">
      </a>
      <div class="card-body">
        <h5 class="card-title"><b>Answering Business Questions using SQL</b></h5>
        <h6><i>skill: sql</i></h6>
        <p class="card-text">This was a project completed in the DataQuest.io Data
          Engineering Career Path program.</p>
      </div>
    </div>
  </div>
</section>
<br>
<br>

<section id="presentations">
  <h2 id='section-header'>Presentations</h2>
  <hr>
  <dl>
    <dt>October 12th, 2021 - <a href="https://pybit.es/catalogue/the-pdm-program/">Python Developer Mindset</a> Code Clinic</dt>
      <dd>- Test Driven Development of Django Projects
        <a href="https://github.com/claytoncook12/PDMPresentation202108">
          (Code and Presentation)
        </a>
      </dd>
  </dl>
</section>
<br>
<br>

<section id='skills'>
  <h2 id='section-header'>Skills</h2>
  <hr>
  <dl>
    <dt>Programming Languages</dt>
      <dd>- Python</dd>
      <dd>- SQL</dd>
    <dt>Data Analysis</dt>
      <dd>- Pandas</dd>
    <dt>Databases</dt>
      <dd>- SQLite3</dd>
      <dd>- PostgreSQL</dd>
      <dd>- gINT (geotechnical engineering specific)</dd>
    <dt>Docker</dt>
    <dt>Web Frameworks</dt>
      <dd>- Django</dd>
    <dt>Amazon Web Services</dt>
      <dd>- EC2</dd>
      <dd>- Elastic Beanstalk</dd>
      <dd>- S3</dd>
    <dt>Code Editor</dt>
      <dd>- Visual Studio Code</dd>
    <dt>Version Control</dt>
      <dd>- git</dd>
  </dl>  
</section>



{% endblock %}

DjangoApp/templates/music_base.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% block music_content %}
{% endblock %}
{% endblock %}

DjangoApp/templates/music_home.html
{% extends 'music_base.html' %}
{% load static %}

{% block music_content %}
<h1
    style="text-align: center;"
>
    Music
</h1>

<p
    style="text-align: left;"
>
    I love playing music. In the last couple of years I have really
    dived head first into learning Irish music. I got the introductory
    insturment, the tin whistle, and moved onto learning the flute
    as well. Such fun music and people.
    <br><br>
    I have started to put together a tune book to write down the tunes
    that I know, how I play them, and resources I have found useful in learning
    and playing the music.
    <br><br>
    Hope you find it useful as well.
    <br><br>
    <div
        style="text-align: center;"
    >
        <h2>
            <a href="{% url 'tunes:list' %}">
                Tunes List
            </a>
        </h2>
    </div>
</p>
{% endblock %}